In [4]:
import pandas as pd
df = pd.read_csv('sales_data_sample.csv', encoding='ISO-8859-1')
display(df)

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,15,2244.40,12/2/2004 0:00,Shipped,4,12,2004,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,1,1,2005,...,Torikatu 38,NaN,Oulu,NaN,90110,Finland,EMEA,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5417.57,3/1/2005 0:00,Resolved,1,3,2005,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,1 rue Alsace-Lorraine,NaN,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,5/6/2005 0:00,On Hold,2,5,2005,...,8616 Spinnaker Dr.,NaN,Boston,MA,51003,USA,NaN,Yoshido,Juri,Medium

In [5]:
import pandas as pd
df = pd.read_csv('sales_data_sample.csv', encoding='ISO-8859-1')
#data of the first 5 rows
display(df.head(5))

#data of last 5 rows
display(df.tail(5))

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
2818,10350,20,100.00,15,2244.40,12/2/2004 0:00,Shipped,4,12,2004,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,1,1,2005,...,Torikatu 38,NaN,Oulu,NaN,90110,Finland,EMEA,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5417.57,3/1/2005 0:00,Resolved,1,3,2005,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,1 rue Alsace-Lorraine,NaN,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,5/6/2005 0:00,On Hold,2,5,2005,...,8616 Spinnaker Dr.,NaN,Boston,MA,51003,USA,NaN,Yoshido,Juri,Medium

In [6]:
import pandas as pd
df = pd.read_csv("sales_data_sample.csv", encoding="ISO-8859-1")
display(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 2823 entries, 0 to 2822
Data columns (total 25 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ORDERNUMBER       2823 non-null   int64
 1   QUANTITYORDERED   2823 non-null   int64
 2   PRICEEACH         2823 non-null   float64
 3   ORDERLINENUMBER   2823 non-null   int64
 4   SALES             2823 non-null   float64
 5   ORDERDATE         2823 non-null   str
 6   STATUS            2823 non-null   str
 7   QTR_ID            2823 non-null   int64
 8   MONTH_ID          2823 non-null   int64
 9   YEAR_ID           2823 non-null   int64
 10  PRODUCTLINE       2823 non-null   str
 11  MSRP              2823 non-null   int64
 12  PRODUCTCODE       2823 non-null   str
 13  CUSTOMERNAME      2823 non-null   str
 14  PHONE             2823 non-null   str
 15  ADDRESSLINE1      2823 non-null   str
 16  ADDRESSLINE2      302 non-null    str
 17  CITY              2823 non-null   str
 18  STATE             1337 non-null   str
 19  POSTALCODE        2747 non-null   str
 20  COUNTRY           2823 non-null   str
 21  TERRITORY         1749 non-null   str
 22  CONTACTLASTNAME   2823 non-null   str
 23  CONTACTFIRSTNAME  2823 non-null   str
 24  DEALSIZE          2823 non-null   str
dtypes: float64(2), int64(7), str(16)
memory usage: 551.5 KB

None

In [7]:
import pandas as pd
df = pd.read_csv("sales_data_sample.csv", encoding="ISO-8859-1")


display(df)

print("describe function\n")

print(df.describe())

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,15,2244.40,12/2/2004 0:00,Shipped,4,12,2004,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,1,1,2005,...,Torikatu 38,NaN,Oulu,NaN,90110,Finland,EMEA,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5417.57,3/1/2005 0:00,Resolved,1,3,2005,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,1 rue Alsace-Lorraine,NaN,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,5/6/2005 0:00,On Hold,2,5,2005,...,8616 Spinnaker Dr.,NaN,Boston,MA,51003,USA,NaN,Yoshido,Juri,Medium

describe function

        ORDERNUMBER  QUANTITYORDERED    PRICEEACH  ORDERLINENUMBER  \
count   2823.000000      2823.000000  2823.000000      2823.000000
mean   10258.725115        35.092809    83.658544         6.466171
std       92.085478         9.741443    20.174277         4.225841
min    10100.000000         6.000000    26.880000         1.000000
25%    10180.000000        27.000000    68.860000         3.000000
50%    10262.000000        35.000000    95.700000         6.000000
75%    10333.500000        43.000000   100.000000         9.000000
max    10425.000000        97.000000   100.000000        18.000000

              SALES       QTR_ID     MONTH_ID     YEAR_ID         MSRP
count   2823.000000  2823.000000  2823.000000  2823.00000  2823.000000
mean    3553.889072     2.717676     7.092455  2003.81509   100.715551
std     1841.865106     1.203878     3.656633     0.69967    40.187912
min      482.130000     1.000000     1.000000  2003.00000    33.000000
25%     2203.430000     2.000000     4.000000  2003.00000    68.000000
50%     3184.800000     3.000000     8.000000  2004.00000    99.000000
75%     4508.000000     4.000000    11.000000  2004.00000   124.000000
max    14082.800000     4.000000    12.000000  2005.00000   214.000000

In [8]:
import pandas as pd
df = pd.read_csv("sales_data_sample.csv", encoding="ISO-8859-1")

print(f"shape:{df.shape}")
print(f"Columns names: {df.columns}")

shape:(2823, 25)
Columns names: Index(['ORDERNUMBER', 'QUANTITYORDERED', 'PRICEEACH', 'ORDERLINENUMBER',
       'SALES', 'ORDERDATE', 'STATUS', 'QTR_ID', 'MONTH_ID', 'YEAR_ID',
       'PRODUCTLINE', 'MSRP', 'PRODUCTCODE', 'CUSTOMERNAME', 'PHONE',
       'ADDRESSLINE1', 'ADDRESSLINE2', 'CITY', 'STATE', 'POSTALCODE',
       'COUNTRY', 'TERRITORY', 'CONTACTLASTNAME', 'CONTACTFIRSTNAME',
       'DEALSIZE'],
      dtype='str')

In [9]:
import pandas as pd

data ={
    "Name":['naman','aman','ram','shyam','amit','ankit','arun','rohit','mohit','krish'],
    "Age":[23,22,32,19,20,23,22,26,24,25],
    "Salary":[56000,340000,36000,43000,41000,44000,45000,42000,39000,40000],
    "Performence_Score":[80,90,92,87,85,88,84,83,84,88]
}

df = pd.DataFrame(data)
print(df)

print("\n")

#printing all names

#print(df["Name"])

#printing all Names with their salary 

#print(df[["Name","Salary"]])

    Name  Age  Salary  Performence_Score
0  naman   23   56000                 80
1   aman   22  340000                 90
2    ram   32   36000                 92
3  shyam   19   43000                 87
4   amit   20   41000                 85
5  ankit   23   44000                 88
6   arun   22   45000                 84
7  rohit   26   42000                 83
8  mohit   24   39000                 84
9  krish   25   40000                 88

#rows data filter

In [10]:
import pandas as pd

data ={
    "Name":['naman','aman','ram','shyam','amit','ankit','arun','rohit','mohit','krish'],
    "Age":[23,22,32,19,20,23,22,26,24,25],
    "Salary":[56000,340000,36000,43000,41000,44000,45000,42000,39000,40000],
    "Performence_Score":[80,90,92,87,85,88,84,83,84,88]
}

df = pd.DataFrame(data)
print(df)

print("\n\n\n")
high_salary = df[df["Salary"]>40000]
print("Employee Salary high than 40k ")
print(high_salary.to_string(index=False))

    Name  Age  Salary  Performence_Score
0  naman   23   56000                 80
1   aman   22  340000                 90
2    ram   32   36000                 92
3  shyam   19   43000                 87
4   amit   20   41000                 85
5  ankit   23   44000                 88
6   arun   22   45000                 84
7  rohit   26   42000                 83
8  mohit   24   39000                 84
9  krish   25   40000                 88




Employee Salary high than 40k
 Name  Age  Salary  Performence_Score
naman   23   56000                 80
 aman   22  340000                 90
shyam   19   43000                 87
 amit   20   41000                 85
ankit   23   44000                 88
 arun   22   45000                 84
rohit   26   42000                 83

In [11]:
import pandas as pd

data ={
    "Name":['naman','aman','ram','shyam','amit','ankit','arun','rohit','mohit','krish'],
    "Age":[23,22,32,19,20,23,22,26,24,25],
    "Salary":[56000,340000,36000,43000,41000,44000,45000,42000,39000,40000],
    "Performence_Score":[80,90,92,87,85,88,84,83,84,88]
}

df = pd.DataFrame(data)


print("\n")

df['Bonus']=df['Salary']*.1

print(df)



#using insert method which give us more ability to add column data to any location
df.insert(0,"Employee_Id",[1,2,3,4,5,6,7,8,9,10])

print("\n\n")
print(df)

    Name  Age  Salary  Performence_Score    Bonus
0  naman   23   56000                 80   5600.0
1   aman   22  340000                 90  34000.0
2    ram   32   36000                 92   3600.0
3  shyam   19   43000                 87   4300.0
4   amit   20   41000                 85   4100.0
5  ankit   23   44000                 88   4400.0
6   arun   22   45000                 84   4500.0
7  rohit   26   42000                 83   4200.0
8  mohit   24   39000                 84   3900.0
9  krish   25   40000                 88   4000.0



   Employee_Id   Name  Age  Salary  Performence_Score    Bonus
0            1  naman   23   56000                 80   5600.0
1            2   aman   22  340000                 90  34000.0
2            3    ram   32   36000                 92   3600.0
3            4  shyam   19   43000                 87   4300.0
4            5   amit   20   41000                 85   4100.0
5            6  ankit   23   44000                 88   4400.0
6            7   arun   22   45000                 84   4500.0
7            8  rohit   26   42000                 83   4200.0
8            9  mohit   24   39000                 84   3900.0
9           10  krish   25   40000                 88   4000.0

Updating in pandas

In [12]:
import pandas as pd

data ={
    "Name":['naman','aman','ram','shyam','amit','ankit','arun','rohit','mohit','krish'],
    "Age":[23,22,32,19,20,23,22,26,24,25],
    "Salary":[56000,340000,36000,43000,41000,44000,45000,42000,39000,40000],
    "Performence_Score":[80,90,92,87,85,88,84,83,84,88]
}

df = pd.DataFrame(data)


print("\n")

df.loc[1,"Salary"]=55000

print(df)
print("\n")

#updating all column

df["Salary"] = df['Salary']*1.10
print(df)

    Name  Age  Salary  Performence_Score
0  naman   23   56000                 80
1   aman   22   55000                 90
2    ram   32   36000                 92
3  shyam   19   43000                 87
4   amit   20   41000                 85
5  ankit   23   44000                 88
6   arun   22   45000                 84
7  rohit   26   42000                 83
8  mohit   24   39000                 84
9  krish   25   40000                 88


    Name  Age   Salary  Performence_Score
0  naman   23  61600.0                 80
1   aman   22  60500.0                 90
2    ram   32  39600.0                 92
3  shyam   19  47300.0                 87
4   amit   20  45100.0                 85
5  ankit   23  48400.0                 88
6   arun   22  49500.0                 84
7  rohit   26  46200.0                 83
8  mohit   24  42900.0                 84
9  krish   25  44000.0                 88

# Removing column

In [13]:
import pandas as pd

data ={
    "Name":['naman','aman','ram','shyam','amit','ankit','arun','rohit','mohit','krish'],
    "Age":[23,22,32,19,20,23,22,26,24,25],
    "Salary":[56000,340000,36000,43000,41000,44000,45000,42000,39000,40000],
    "Performence_Score":[80,90,92,87,85,88,84,83,84,88]
}

df = pd.DataFrame(data)

print(df)
print("\n")


df.drop(columns=["Performence_Score","Age"],inplace=True)

print("Modified data ")
print(df)

    Name  Age  Salary  Performence_Score
0  naman   23   56000                 80
1   aman   22  340000                 90
2    ram   32   36000                 92
3  shyam   19   43000                 87
4   amit   20   41000                 85
5  ankit   23   44000                 88
6   arun   22   45000                 84
7  rohit   26   42000                 83
8  mohit   24   39000                 84
9  krish   25   40000                 88


Modified data
    Name  Salary
0  naman   56000
1   aman  340000
2    ram   36000
3  shyam   43000
4   amit   41000
5  ankit   44000
6   arun   45000
7  rohit   42000
8  mohit   39000
9  krish   40000

# Handling missing data

In [14]:
import pandas as pd

data ={
    "Name":['naman','aman','ram','shyam','amit','ankit','arun','rohit','mohit','krish'],
    "Age":[23,22,32,19,20,23,22,26,24,25],
    "Salary":[56000,340000,None,43000,41000,44000,45000,42000,39000,40000],
    "Performence_Score":[80,None,92,87,85,88,84,83,84,88]
}

df = pd.DataFrame(data)

print(df)
print("\n")




print(df.isnull())

print(df.isnull().sum())

    Name  Age    Salary  Performence_Score
0  naman   23   56000.0               80.0
1   aman   22  340000.0                NaN
2    ram   32       NaN               92.0
3  shyam   19   43000.0               87.0
4   amit   20   41000.0               85.0
5  ankit   23   44000.0               88.0
6   arun   22   45000.0               84.0
7  rohit   26   42000.0               83.0
8  mohit   24   39000.0               84.0
9  krish   25   40000.0               88.0

    Name    Age  Salary  Performence_Score
0  False  False   False              False
1  False  False   False               True
2  False  False    True              False
3  False  False   False              False
4  False  False   False              False
5  False  False   False              False
6  False  False   False              False
7  False  False   False              False
8  False  False   False              False
9  False  False   False              False
Name                 0
Age                  0
Salary               1
Performence_Score    1
dtype: int64

# handling none value

In [15]:
import pandas as pd

data ={
    "Name":['naman','aman','Ram','shyam','amit','ankit','arun','rohit','mohit','krish'],
    "Age":[23,22,32,19,20,23,22,26,24,25],
    "Salary":[56000,340000,None,43000,41000,44000,45000,42000,39000,40000],
    "Performence_Score":[80,None,92,87,85,88,84,83,84,88]
}

df = pd.DataFrame(data)

print(df)
print("\n")

#By Using drop 

# df.dropna(inplace=True)
# print(df)


#by using fill any particular data
df.fillna(0,inplace=True)
print(df)


# Fill string column
df["Name"] = df["Name"].fillna("Unknown")

# Fill numeric columns
df["Salary"] = df["Salary"].fillna(0)
#df["Performance_Score"] = df["Performance_Score"].fillna(0)
df['Performence_Score']=df['Performence_Score'].fillna(0)
print(df)

    Name  Age    Salary  Performence_Score
0  naman   23   56000.0               80.0
1   aman   22  340000.0                NaN
2    Ram   32       NaN               92.0
3  shyam   19   43000.0               87.0
4   amit   20   41000.0               85.0
5  ankit   23   44000.0               88.0
6   arun   22   45000.0               84.0
7  rohit   26   42000.0               83.0
8  mohit   24   39000.0               84.0
9  krish   25   40000.0               88.0


    Name  Age    Salary  Performence_Score
0  naman   23   56000.0               80.0
1   aman   22  340000.0                0.0
2    Ram   32       0.0               92.0
3  shyam   19   43000.0               87.0
4   amit   20   41000.0               85.0
5  ankit   23   44000.0               88.0
6   arun   22   45000.0               84.0
7  rohit   26   42000.0               83.0
8  mohit   24   39000.0               84.0
9  krish   25   40000.0               88.0
    Name  Age    Salary  Performence_Score
0  naman   23   56000.0               80.0
1   aman   22  340000.0                0.0
2    Ram   32       0.0               92.0
3  shyam   19   43000.0               87.0
4   amit   20   41000.0               85.0
5  ankit   23   44000.0               88.0
6   arun   22   45000.0               84.0
7  rohit   26   42000.0               83.0
8  mohit   24   39000.0               84.0
9  krish   25   40000.0               88.0

# Interpolation

In [16]:
import pandas as pd
data = {
    'Time':[1,2,3,4,5],
    'value':[10,20,None,30,50]
}

df=pd.DataFrame(data)

print("Before Interpolation")
print(df)

print("\nAfter Interpolation")
df["value"]=df["value"].interpolate(method="linear")
print(df)

Before Interpolation
   Time  value
0     1   10.0
1     2   20.0
2     3    NaN
3     4   30.0
4     5   50.0

After Interpolation
   Time  value
0     1   10.0
1     2   20.0
2     3   25.0
3     4   30.0
4     5   50.0

# Sorting of data

In [17]:
import pandas as pd


data ={
    "Name":['Naman','Aman','Rohan'],
    "Age":[23,22,29],
    'Salary':[20000,39000,15000]
}

df=pd.DataFrame(data)


print("Sorting Age in  ascending order ")
df.sort_values(by='Age',ascending=True,inplace=True)

print(df)

Sorting Age in  ascending order
    Name  Age  Salary
1   Aman   22   39000
0  Naman   23   20000
2  Rohan   29   15000

# Aggregation in pandas

In [18]:
'''df["column name"].mean()
    df["column name"].sum()
    df["column name"].min()
    df["column name"].max()



'''



import pandas as pd
data ={
    "Name":['Naman','Aman','Rohan'],
    "Age":[23,22,29],
    'Salary':[20000,39000,15000]
}

df=pd.DataFrame(data)

avg_age= df["Age"].mean()

print(f"The avg age is {avg_age}")

The avg age is 24.666666666666668

# groupby function

In [21]:
import pandas as pd
data ={
    "Name":['Naman','Aman','Rohan'],
    "Age":[23,22,29],
    'Salary':[20000,39000,15000]
}

df=pd.DataFrame(data)
#single column
grouped = df.groupby("Age")["Salary"].sum()

print(grouped)

#multiple group

group = df.groupby(['Age',"Name"])["Salary"].sum()
print(group)

Age
22    39000
23    20000
29    15000
Name: Salary, dtype: int64
Age  Name
22   Aman     39000
23   Naman    20000
29   Rohan    15000
Name: Salary, dtype: int64

# Merging the data

In [7]:

''''
types of joins
1. Inner
2.outer
3.cross
4.right
5.left
'''

import pandas as pd

df_customer = pd.DataFrame({
    'Customer_id':[1,2,3],
    'Customer_name':["Ram","Shyam","Aman"]
})

df_order = pd.DataFrame({
    'Customer_id':[1,2,4],
    'Amount':[450,499,900]
})


#merge
df_merge= pd.merge(df_customer,df_order,on="Customer_id",how="inner")
print("Inner join")
print(df_merge)

Inner join
   Customer_id Customer_name  Amount
0            1           Ram     450
1            2         Shyam     499

1
2
4
5
5
6
7